export type RegionInfo = { code: string; name: string; default_timezone_iana: string };

export const US_STATES: RegionInfo[] = [
  { code: 'AL', name: 'Alabama', default_timezone_iana: 'America/Chicago' },
  { code: 'AK', name: 'Alaska', default_timezone_iana: 'America/Anchorage' },
  { code: 'AZ', name: 'Arizona', default_timezone_iana: 'America/Phoenix' },
  { code: 'AR', name: 'Arkansas', default_timezone_iana: 'America/Chicago' },
  { code: 'CA', name: 'California', default_timezone_iana: 'America/Los_Angeles' },
  { code: 'CO', name: 'Colorado', default_timezone_iana: 'America/Denver' },
  { code: 'CT', name: 'Connecticut', default_timezone_iana: 'America/New_York' },
  { code: 'DE', name: 'Delaware', default_timezone_iana: 'America/New_York' },
  { code: 'DC', name: 'District of Columbia', default_timezone_iana: 'America/New_York' },
  { code: 'FL', name: 'Florida', default_timezone_iana: 'America/New_York' },
  { code: 'GA', name: 'Georgia', default_timezone_iana: 'America/New_York' },
  { code: 'HI', name: 'Hawaii', default_timezone_iana: 'Pacific/Honolulu' },
  { code: 'ID', name: 'Idaho', default_timezone_iana: 'America/Boise' },
  { code: 'IL', name: 'Illinois', default_timezone_iana: 'America/Chicago' },
  { code: 'IN', name: 'Indiana', default_timezone_iana: 'America/Indiana/Indianapolis' },
  { code: 'IA', name: 'Iowa', default_timezone_iana: 'America/Chicago' },
  { code: 'KS', name: 'Kansas', default_timezone_iana: 'America/Chicago' },
  { code: 'KY', name: 'Kentucky', default_timezone_iana: 'America/New_York' },
  { code: 'LA', name: 'Louisiana', default_timezone_iana: 'America/Chicago' },
  { code: 'ME', name: 'Maine', default_timezone_iana: 'America/New_York' },
  { code: 'MD', name: 'Maryland', default_timezone_iana: 'America/New_York' },
  { code: 'MA', name: 'Massachusetts', default_timezone_iana: 'America/New_York' },
  { code: 'MI', name: 'Michigan', default_timezone_iana: 'America/Detroit' },
  { code: 'MN', name: 'Minnesota', default_timezone_iana: 'America/Chicago' },
  { code: 'MS', name: 'Mississippi', default_timezone_iana: 'America/Chicago' },
  { code: 'MO', name: 'Missouri', default_timezone_iana: 'America/Chicago' },
  { code: 'MT', name: 'Montana', default_timezone_iana: 'America/Denver' },
  { code: 'NE', name: 'Nebraska', default_timezone_iana: 'America/Chicago' },
  { code: 'NV', name: 'Nevada', default_timezone_iana: 'America/Los_Angeles' },
  { code: 'NH', name: 'New Hampshire', default_timezone_iana: 'America/New_York' },
  { code: 'NJ', name: 'New Jersey', default_timezone_iana: 'America/New_York' },
  { code: 'NM', name: 'New Mexico', default_timezone_iana: 'America/Denver' },
  { code: 'NY', name: 'New York', default_timezone_iana: 'America/New_York' },
  { code: 'NC', name: 'North Carolina', default_timezone_iana: 'America/New_York' },
  { code: 'ND', name: 'North Dakota', default_timezone_iana: 'America/Chicago' },
  { code: 'OH', name: 'Ohio', default_timezone_iana: 'America/New_York' },
  { code: 'OK', name: 'Oklahoma', default_timezone_iana: 'America/Chicago' },
  { code: 'OR', name: 'Oregon', default_timezone_iana: 'America/Los_Angeles' },
  { code: 'PA', name: 'Pennsylvania', default_timezone_iana: 'America/New_York' },
  { code: 'RI', name: 'Rhode Island', default_timezone_iana: 'America/New_York' },
  { code: 'SC', name: 'South Carolina', default_timezone_iana: 'America/New_York' },
  { code: 'SD', name: 'South Dakota', default_timezone_iana: 'America/Chicago' },
  { code: 'TN', name: 'Tennessee', default_timezone_iana: 'America/Chicago' },
  { code: 'TX', name: 'Texas', default_timezone_iana: 'America/Chicago' },
  { code: 'UT', name: 'Utah', default_timezone_iana: 'America/Denver' },
  { code: 'VT', name: 'Vermont', default_timezone_iana: 'America/New_York' },
  { code: 'VA', name: 'Virginia', default_timezone_iana: 'America/New_York' },
  { code: 'WA', name: 'Washington', default_timezone_iana: 'America/Los_Angeles' },
  { code: 'WV', name: 'West Virginia', default_timezone_iana: 'America/New_York' },
  { code: 'WI', name: 'Wisconsin', default_timezone_iana: 'America/Chicago' },
  { code: 'WY', name: 'Wyoming', default_timezone_iana: 'America/Denver' },
];
