// Static data file; 200-line ceiling rule does not apply to data files.

export const AU_CITIES: Record<string, string[]> = {
  'NSW': [
    'Sydney',
    'Newcastle',
    'Central Coast',
    'Wollongong',
    'Maitland',
    'Wagga Wagga',
    'Albury',
    'Port Macquarie',
    'Tamworth',
    'Orange',
    'Dubbo',
    'Bathurst',
    'Lismore',
    'Coffs Harbour',
    'Nowra',
    'Queanbeyan',
    'Broken Hill',
    'Goulburn',
    'Armidale',
    'Griffith',
  ],
  'VIC': [
    'Melbourne',
    'Geelong',
    'Ballarat',
    'Bendigo',
    'Shepparton',
    'Wodonga',
    'Mildura',
    'Warrnambool',
    'Frankston',
    'Dandenong',
    'Sunbury',
    'Pakenham',
    'Cranbourne',
    'Sale',
    'Traralgon',
    'Horsham',
    'Latrobe',
    'Wangaratta',
    'Echuca',
    'Moe',
  ],
  'QLD': [
    'Brisbane',
    'Gold Coast',
    'Sunshine Coast',
    'Townsville',
    'Cairns',
    'Toowoomba',
    'Mackay',
    'Rockhampton',
    'Bundaberg',
    'Hervey Bay',
    'Gladstone',
    'Mount Isa',
    'Maryborough',
    'Ipswich',
    'Logan',
    'Redcliffe',
    'Caboolture',
  ],
  'WA': [
    'Perth',
    'Mandurah',
    'Bunbury',
    'Geraldton',
    'Kalgoorlie',
    'Albany',
    'Busselton',
    'Karratha',
    'Port Hedland',
    'Broome',
    'Rockingham',
    'Joondalup',
    'Fremantle',
  ],
  'SA': [
    'Adelaide',
    'Mount Gambier',
    'Whyalla',
    'Murray Bridge',
    'Port Augusta',
    'Port Lincoln',
    'Port Pirie',
    'Victor Harbor',
    'Gawler',
    'Mount Barker',
  ],
  'TAS': [
    'Hobart',
    'Launceston',
    'Devonport',
    'Burnie',
    'Ulverstone',
    'Kingston',
    'Glenorchy',
    'New Norfolk',
  ],
  'ACT': [
    'Canberra',
    'Belconnen',
    'Tuggeranong',
    'Gungahlin',
    'Woden',
    'Queanbeyan',
  ],
  'NT': [
    'Darwin',
    'Alice Springs',
    'Palmerston',
    'Katherine',
    'Nhulunbuy',
    'Tennant Creek',
  ],
};
