// Static data file; 200-line ceiling rule does not apply to data files.

export const CA_CITIES: Record<string, string[]> = {
  'ON': [
    'Toronto',
    'Ottawa',
    'Mississauga',
    'Brampton',
    'Hamilton',
    'London',
    'Markham',
    'Vaughan',
    'Kitchener',
    'Windsor',
    'Richmond Hill',
    'Oakville',
    'Burlington',
    'Greater Sudbury',
    'Oshawa',
    'Barrie',
    'St. Catharines',
    'Cambridge',
    'Kingston',
    'Whitby',
    'Guelph',
    'Ajax',
    'Thunder Bay',
    'Waterloo',
    'Brantford',
    'Pickering',
    'Niagara Falls',
    'Newmarket',
    'Peterborough',
    'Sarnia',
    'Sault Ste. Marie',
    'North Bay',
    'Belleville',
    'Cornwall',
    'Chatham',
    'Orillia',
  ],
  'QC': [
    'Montreal',
    'Quebec City',
    'Laval',
    'Gatineau',
    'Longueuil',
    'Sherbrooke',
    'Saguenay',
    'Levis',
    'Trois-Rivieres',
    'Terrebonne',
    'Saint-Jean-sur-Richelieu',
    'Repentigny',
    'Brossard',
    'Drummondville',
    'Saint-Jerome',
    'Granby',
    'Blainville',
    'Saint-Hyacinthe',
    'Shawinigan',
    'Dollard-des-Ormeaux',
    'Rimouski',
    'Victoriaville',
  ],
  'BC': [
    'Vancouver',
    'Surrey',
    'Burnaby',
    'Richmond',
    'Abbotsford',
    'Coquitlam',
    'Kelowna',
    'Victoria',
    'Saanich',
    'Langley',
    'Delta',
    'Kamloops',
    'Nanaimo',
    'Chilliwack',
    'Maple Ridge',
    'Prince George',
    'New Westminster',
    'North Vancouver',
    'Port Coquitlam',
    'Vernon',
    'Courtenay',
    'Penticton',
    'Campbell River',
  ],
  'AB': [
    'Calgary',
    'Edmonton',
    'Red Deer',
    'Lethbridge',
    'St. Albert',
    'Medicine Hat',
    'Grande Prairie',
    'Airdrie',
    'Spruce Grove',
    'Fort McMurray',
    'Okotoks',
    'Lloydminster',
    'Camrose',
    'Brooks',
    'Cold Lake',
    'Lacombe',
    'Wetaskiwin',
    'Canmore',
  ],
  'MB': [
    'Winnipeg',
    'Brandon',
    'Steinbach',
    'Thompson',
    'Portage la Prairie',
    'Winkler',
    'Selkirk',
    'Morden',
    'Dauphin',
    'The Pas',
  ],
  'SK': [
    'Saskatoon',
    'Regina',
    'Prince Albert',
    'Moose Jaw',
    'Swift Current',
    'Yorkton',
    'North Battleford',
    'Estevan',
    'Weyburn',
    'Lloydminster',
  ],
  'NS': [
    'Halifax',
    'Dartmouth',
    'Sydney',
    'Truro',
    'New Glasgow',
    'Glace Bay',
    'Kentville',
    'Amherst',
    'Bridgewater',
    'Yarmouth',
  ],
  'NB': [
    'Moncton',
    'Saint John',
    'Fredericton',
    'Dieppe',
    'Miramichi',
    'Edmundston',
    'Bathurst',
    'Campbellton',
    'Quispamsis',
    'Riverview',
  ],
  'NL': [
    'St. John\'s',
    'Mount Pearl',
    'Corner Brook',
    'Grand Falls-Windsor',
    'Gander',
    'Paradise',
    'Conception Bay South',
    'Happy Valley-Goose Bay',
    'Labrador City',
    'Stephenville',
  ],
  'PE': [
    'Charlottetown',
    'Summerside',
    'Stratford',
    'Cornwall',
    'Montague',
    'Kensington',
    'Souris',
  ],
  'NT': [
    'Yellowknife',
    'Hay River',
    'Inuvik',
    'Fort Smith',
    'Behchoko',
    'Norman Wells',
  ],
  'YT': [
    'Whitehorse',
    'Dawson City',
    'Watson Lake',
    'Haines Junction',
    'Carmacks',
    'Mayo',
  ],
  'NU': [
    'Iqaluit',
    'Rankin Inlet',
    'Arviat',
    'Baker Lake',
    'Cambridge Bay',
    'Pangnirtung',
    'Pond Inlet',
  ],
};
