// Static data file; 200-line ceiling rule does not apply to data files.

export const UK_CITIES: Record<string, string[]> = {
  'ENG-LON': [
    'London',
    'Croydon',
    'Bromley',
    'Ealing',
    'Enfield',
    'Barnet',
    'Waltham Forest',
    'Redbridge',
    'Greenwich',
    'Lewisham',
    'Southwark',
    'Lambeth',
    'Wandsworth',
    'Hammersmith',
    'Kensington',
    'Westminster',
    'Camden',
    'Islington',
    'Hackney',
    'Tower Hamlets',
    'Newham',
    'Barking',
    'Havering',
    'Hillingdon',
    'Hounslow',
    'Kingston upon Thames',
    'Merton',
    'Sutton',
    'Richmond upon Thames',
    'Harrow',
    'Brent',
  ],
  'ENG-SE': [
    'Brighton',
    'Reading',
    'Oxford',
    'Southampton',
    'Portsmouth',
    'Milton Keynes',
    'Slough',
    'Basingstoke',
    'Crawley',
    'Maidstone',
    'Canterbury',
    'Guildford',
    'Eastbourne',
    'Worthing',
    'Hastings',
    'Woking',
    'High Wycombe',
    'Aylesbury',
    'Farnborough',
    'Chatham',
    'Gillingham',
  ],
  'ENG-SW': [
    'Bristol',
    'Plymouth',
    'Bournemouth',
    'Poole',
    'Swindon',
    'Gloucester',
    'Exeter',
    'Cheltenham',
    'Bath',
    'Taunton',
    'Weston-super-Mare',
    'Torquay',
    'Salisbury',
    'Truro',
    'Yeovil',
    'Weymouth',
  ],
  'ENG-EM': [
    'Nottingham',
    'Leicester',
    'Derby',
    'Northampton',
    'Lincoln',
    'Loughborough',
    'Mansfield',
    'Chesterfield',
    'Boston',
    'Kettering',
    'Corby',
    'Grantham',
    'Worksop',
    'Newark',
  ],
  'ENG-WM': [
    'Birmingham',
    'Coventry',
    'Wolverhampton',
    'Stoke-on-Trent',
    'Walsall',
    'Dudley',
    'Solihull',
    'Telford',
    'West Bromwich',
    'Worcester',
    'Hereford',
    'Nuneaton',
    'Rugby',
    'Tamworth',
    'Stafford',
  ],
  'ENG-EE': [
    'Norwich',
    'Ipswich',
    'Cambridge',
    'Peterborough',
    'Luton',
    'Colchester',
    'Southend-on-Sea',
    'Basildon',
    'Watford',
    'Stevenage',
    'Bedford',
    'Chelmsford',
    'Harlow',
    'St Albans',
    'Hemel Hempstead',
  ],
  'ENG-NE': [
    'Newcastle upon Tyne',
    'Sunderland',
    'Middlesbrough',
    'Gateshead',
    'Hartlepool',
    'Darlington',
    'South Shields',
    'Stockton-on-Tees',
    'Durham',
    'Washington',
    'Blyth',
    'Ashington',
    'Redcar',
  ],
  'ENG-NW': [
    'Manchester',
    'Liverpool',
    'Bolton',
    'Stockport',
    'Salford',
    'Oldham',
    'Blackpool',
    'Preston',
    'Warrington',
    'Blackburn',
    'Wigan',
    'Rochdale',
    'Bury',
    'Burnley',
    'Chester',
    'Lancaster',
    'Crewe',
    'Macclesfield',
    'Southport',
    'St Helens',
  ],
  'ENG-YH': [
    'Leeds',
    'Sheffield',
    'Bradford',
    'Kingston upon Hull',
    'York',
    'Wakefield',
    'Huddersfield',
    'Doncaster',
    'Rotherham',
    'Barnsley',
    'Halifax',
    'Scarborough',
    'Harrogate',
    'Grimsby',
    'Scunthorpe',
  ],
  'SCT': [
    'Edinburgh',
    'Glasgow',
    'Aberdeen',
    'Dundee',
    'Stirling',
    'Perth',
    'Inverness',
    'Paisley',
    'East Kilbride',
    'Livingston',
    'Hamilton',
    'Cumbernauld',
    'Kirkcaldy',
    'Dunfermline',
    'Ayr',
    'Kilmarnock',
    'Greenock',
    'Dumfries',
    'Falkirk',
    'Motherwell',
  ],
  'WLS': [
    'Cardiff',
    'Swansea',
    'Newport',
    'Wrexham',
    'Barry',
    'Caerphilly',
    'Bridgend',
    'Llanelli',
    'Merthyr Tydfil',
    'Bangor',
    'Aberystwyth',
    'Neath',
    'Port Talbot',
    'Cwmbran',
    'Rhondda',
  ],
  'NIR': [
    'Belfast',
    'Londonderry',
    'Lisburn',
    'Newtownabbey',
    'Bangor',
    'Craigavon',
    'Castlereagh',
    'Ballymena',
    'Newtownards',
    'Carrickfergus',
    'Antrim',
    'Coleraine',
    'Omagh',
    'Enniskillen',
    'Armagh',
    'Dungannon',
  ],
};
