-- §3.15 weekly_insights
-- Claude-generated weekly insight cards shown on the Learning Dashboard
-- (§11.3). Generated by the Monday-6am cron job over the prior week's
-- call_attempts. dismissed_by holds the team-member uuids who clicked
-- "dismiss" on that card.

create table public.weekly_insights (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  week_starting date,
  insight_text text,
  dismissed_by uuid[]
);
